<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX029sbf\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX029sbf/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerX029sbf.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerX029sbf\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerX029sbf\appDevDebugProjectContainer(array(
    'container.build_hash' => 'X029sbf',
    'container.build_id' => '38fef507',
    'container.build_time' => 1546021802,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerX029sbf');
